services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app

  mailpit:
    image: axllent/mailpit:v1.21
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1